MvcApplication1/MvcApplication1/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;
using MvcApplication1.Utils;
using System.Net.Http;
using System.Net;
using System.Net.Http.Formatting;

namespace MvcApplication1.Controllers
{
    public class BrowseController : Controller
    {
        //
        // GET: /Browse/

        public ActionResult Browse()
        {
            return View();
        }

        public ActionResult GetBookList()
        {
            //test list of IDs to populate the list based on test book table
            //int[] IDs = { 1, 2, 3, 4, 5, 6 };

            //List<Book> bookList = new List<Book>();
            //for(int i = 0; i < IDs.Length; i++)
            //{
            //    bookList.Add(BookUtils.getBook(IDs[i]));
            //}

            //ViewData["BookList"] = bookList;
            //ViewData["isListing"] = true;
            //return View("~/Views/Shared/BookList.cshtml");



            List<Book> bookList;
            using (TestDbContext db = new TestDbContext())
            {

                IQueryable<Book> books = from b in db.Books
         //                                      orderby b.BookName
                                               select b;

                bookList = books.ToList<Book>();
                foreach (var b in bookList)
                {
                    if (b != null)
                    {
                        //due to lazy loading, resolve all foreign key references
                        //listing.UserProfile = listing.UserProfile;
                        b.Course = b.Course;
                        b.Course.Books = b.Course.Books;
                    }
                    else
                    {
                        //no listing with the given ID, report error?
                    }
                }
            }


            ViewData["BookList"] = bookList;
            ViewData["isListing"] = true;

            return View("~/Views/Shared/BookList.cshtml");
        }

        public object AutoComplete(string term)
        {
            using(TestDbContext db = new TestDbContext())
            {
                int courseNum;
                bool success;
                success = Int32.TryParse(term, out courseNum);
                var returnArr = db.Books.Where(b => b.BookName.StartsWith(term) ||
                    b.Course.CourseName.StartsWith(term) ||
                    (success && courseNum == b.Course.CourseNumber) ||
                    b.Author.StartsWith(term)).Select(b => new
                    {
                        value = b.BookName.Trim()
                    }).Take(5).ToArray();
               return this.Json(returnArr, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Search(int courseNum = 0, string bookName = "",
                                    string courseName = "", string author = "")
        {
        if (courseNum != 0)
            {
                ViewData["courseNum"] = courseNum;
            }
            if (!bookName.Equals(""))
            {
                ViewData["bookName"] = bookName;
            }
            if (!courseName.Equals(""))
            {
                ViewData["courseName"] = courseName;
            }
            if (!author.Equals(""))
            {
                ViewData["author"] = courseName;
            }
            return View("~/Views/Search/Search.cshtml");
        }

public ActionResult GetListingList(int courseNum = 0, string bookName = "",
                                    string courseName = "", string author = "")
        {
            using(TestDbContext db = new TestDbContext())
            {
                List<Listing> ListingList = db.Listings.Where(b => !bookName.Equals("") && b.Book.BookName.StartsWith(bookName) ||
                       !courseName.Equals("") && b.Book.Course.CourseName.StartsWith(courseName) ||
                       (courseNum == b.Book.Course.CourseNumber) ||
                      !author.Equals("")&& b.Book.Author.StartsWith(author)).ToList();
                for (int i = 0; i < ListingList.Count(); i++)
                {
                    ListingList.ElementAt(i).Book = ListingList.ElementAt(i).Book;
                }
                       ViewData["ListingList"] = ListingList;
                       ViewResult view = View("~/Views/Shared/ListingList.cshtml");
                       return view;
            }
        }

        //book details popup getter
        public ActionResult BookDetails(MvcApplication1.Models.Book clickedBook = null)//)
        {
            if (clickedBook == null)
            {
                return Content("error");
            }
            if (clickedBook.CourseID > 0)
            {
                using (TestDbContext db = new TestDbContext())
                {
                    clickedBook.Course = db.Courses.Find(clickedBook.CourseID);
                }
            }

            
            //get available listings for book

            Book resolvedBook = null;

            using (TestDbContext db = new TestDbContext())
            {

                int accountid = UserUtils.UserNametoID(User.Identity.Name);

                IQueryable<Book> books = from b in db.Books 
                                               where b.BookID == clickedBook.BookID
                                               select b;
                if (books.Count() > 0)
                {
                    resolvedBook = books.First();
                    //probably more loading here than needed
                    resolvedBook.Course = resolvedBook.Course;
                    resolvedBook.Course.Books = resolvedBook.Course.Books;
                    resolvedBook.Listings = resolvedBook.Listings;
                }
                
            }
            
            
            //pass back available listings
            ViewData["book"] = resolvedBook;
            return View("~/Views/Shared/BookDetails.cshtml");
        }

        [HttpGet]
        public ActionResult getBook(string bookName)
        {
            using (TestDbContext db = new TestDbContext())
            {
                Book book;
                var books = (from b in db.Books
                             where b.BookName == bookName
                             select b).ToList();
                if (books.Count > 0 && books[0] != null)
                {
                    book = books[0];

                    book.ISBN = book.ISBN == null ? "" : book.ISBN.Trim();
                    book.Author = book.Author == null ? "" : book.Author.Trim();
                    book.Description = book.Description == null ? "" : book.Description.Trim();

                    if (book.Course == null)
                    {
                        book.Course = new Course();
                        book.Course.CourseName = "";
                    }
                    else if (book.Course.CourseName == null)
                    {
                        book.Course.CourseName = "";
                    }
                }
                else
                {
                    book = new Book();
                    book.BookName = "";
                    book.Course = new Course();
                    book.Course.CourseName = "";
                    book.Author = "";
                    book.ISBN = "";
                    book.Description = "";
                }

                var retBook = new
                {
                    Author = book.Author,
                    ISBN = book.ISBN,
                    CourseName = book.Course.CourseName,
                    Description = book.Description,
                };

                return Json(retBook, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MvcApplication1/MvcApplication1/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;
using MvcApplication1.Utils;

namespace MvcApplication1.Controllers
{
    public class MessageController : Controller
    {
        //
        // GET: /Message/

        public ActionResult Message()
        {
            return View();
        }

        //get sent messages for specified user  
        //GET: /
        [HttpGet]
        public ActionResult GetSentMessages()
        {
            List<Message> msgList;
            string accountname = User.Identity.Name;

            //get list of messages with account id as 
            using (TestDbContext db = new TestDbContext())
            {

                int accountid = UserUtils.UserNametoID(accountname);

                IQueryable<Message> messages = from m in db.Messages
                                               orderby m.SendDate descending
                                               where m.SenderID == accountid
                                               select m;

                msgList = messages.ToList<Message>();

            }

            ViewData["Messages"] = msgList;

            return View("~/Views/Message/MessageList.cshtml");
        }

        //get recieved messages for specified user  
        //GET: /
        [HttpGet]
        public ActionResult GetReceivedMessages()
        {
            List<Message> msgList;
            string accountname = User.Identity.Name;
            
            //get list of messages with account id as 
            using (TestDbContext db = new TestDbContext())
            {

                int accountid = UserUtils.UserNametoID(accountname);

                IQueryable<Message> messages = from m in db.Messages
                                               orderby m.SendDate descending
                                               where m.RecipientID == accountid
                                               select m;

              msgList = messages.ToList<Message>();

            }
            
            ViewData["Messages"] = msgList;
            
            return View("~/Views/Message/MessageList.cshtml");
        }

        //grab web form for sending a message  
        //GET: /
        [HttpGet]
        public ActionResult Compose(string recipient = "no recipient")
        {
            ViewData["Recipient"] = recipient;
            
            return View("~/Views/Message/Compose.cshtml");
        }

        //send a message through a post  
        //GET: /
        [HttpPost]
        public ActionResult Send(string recipient = "no recipient", string sender = "no sender", String message = "empty message")
        {
            //convert recipient name to id
            int recipientid = UserUtils.UserNametoID(recipient);
            string accountname = User.Identity.Name;
            int senderid = UserUtils.UserNametoID(accountname);


            //create a new message object

            //write message to database
            using (TestDbContext db = new TestDbContext())
            {
                db.Messages.Add(new Message{
                    IsRead = false,
                    Message1 = message,
                    RecipientID = recipientid,
                    SendDate = DateTime.Now,
                    SenderID = senderid,
                    SenderName = sender}
                    );

                db.SaveChanges();
            }

            //return View("~/Views/Message/Compose.cshtml");
            return Content("Message Sent");
        
        }

        [HttpPost]
        public ActionResult GetMessage(string id){

            Message myMessage;
            int mid = Convert.ToInt32(id);
            using (TestDbContext db = new TestDbContext())
            {

                IQueryable<Message> messages = from m in db.Messages
                                               orderby m.SendDate
                                               where m.MessageID == mid
                                               select m;

                myMessage = messages.ToList<Message>().First<Message>();


                string replyTarget = "";
                ViewData["currentMessage"] = myMessage;
                string recipient = UserUtils.UserIDtoName(myMessage.RecipientID.Value); ;
                string sender = UserUtils.UserIDtoName(myMessage.SenderID.Value);
                int myID = UserUtils.UserNametoID(User.Identity.Name);
                if (myID == myMessage.RecipientID)
                {
                    replyTarget = sender;

                    //mark message as read
                    myMessage.IsRead = true;
                    db.SaveChanges();
                }
                else
                {
                    replyTarget = recipient;
                }
                ViewData["replyTarget"] = replyTarget; 
          
            }
          
            return View("~/Views/Message/ViewMessage.cshtml");
        }
        //
        // POST:

        [HttpGet]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        public ActionResult AddTwo(int start)
        {
            //get model from db

            int retVal = 0;
            using (  TestDbContext db = new TestDbContext())
            {
                var result = (from b in db.StartDbs
                             select b).FirstOrDefault();
                if (result == null)
                {
                    db.StartDbs.Add(new StartDb { Id = 0, value = 0 });
                    db.SaveChanges();

                }
                else
                {
                    var finalResult = (result as StartDb).value;

                    finalResult += 2;
                    //write back

                    result.value = finalResult;
                    retVal = finalResult;
                    db.SaveChanges();
                }
            }
           
            
            return Content((retVal).ToString());
        }
    }
}

MvcApplication1/MvcApplication1/Views/Shared/BookDetails.cshtml
@{
    Layout = null;
    MvcApplication1.Models.Book book = (MvcApplication1.Models.Book) ViewData["book"];
    List<MvcApplication1.Models.Listing> listings = book.Listings.ToList<MvcApplication1.Models.Listing>();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BookDetails</title>
</head>
<body>
    <div>
        <table>
            <tbody>
                <tr><td>Title: </td><td>@book.BookName</td></tr>
                <tr><td>Author: </td><td>@book.Author</td></tr>
                <tr><td>Description: </td><td>@book.Description</td></tr>
                <tr><td>ISBN: </td><td>@book.ISBN</td></tr>
                <tr /><tr /><tr /><tr />
                <tr><td>Course: </td><td>@book.Course.abbrev()</td></tr>
                <tr><td>Instructor: </td><td>@book.Course.Instructor</td></tr>
            </tbody>
        </table>

        <button id="close">Close</button>
    </div>


<script>
    $('#close').click(function () {
        $('#overlay_parent').css('visibility', 'hidden');
    });
</script>

<h2 >Available Listings:</h2>

<table class="list_box_table">
@{if (listings != null)
  {
      for (int i = 0; i < listings.Count; i++)
      {
          MvcApplication1.Models.Listing listing = listings[i];
    
   		<tr class="list_box_class" @Html.Raw(String.Format("id=\"list_box_{0}\"", i))>
        <td class="thumbnail" >
      		<img src="~/Images/heroAccent.png">
   		</td>
        <td id="Seller" class="seller">
            Sold by @MvcApplication1.Utils.UserUtils.UserIDtoName(listing.UserID):
        </td>
        <td id="Price" class="price">
            @String.Format("{0:C}", listing.Price)
        </td>
        </tr>
<script>
    $(@Html.Raw(String.Format("'#list_box_{0}'", i))).click(function (event) {
        $('#overlay_content').html('<progress max="100"></progress>');
        $('#overlay_parent').css('visibility', 'visible');
        $.post('@Html.Raw(@Url.Action("ListingDetails", "Bookshelf", new { bookID = listing.BookID, seller = listing.UserID, price = listing.Price, BookName = listing.Book.BookName, Author = listing.Book.Author, Description = listing.Book.Description, ISBN = listing.Book.ISBN, CourseID = listing.Book.CourseID, ListID = listing.ListID }))',
                        null, function (result) {
                            $('#overlay_content').html(result);
                        });
    });
</script>

   }
  }
}  
</table>
    
</body>
</html>

MvcApplication1/MvcApplication1/Views/Shared/BookList.cshtml
@{
    Layout = null;
    
    MvcApplication1.Models.Book book;
    List<MvcApplication1.Models.Book> bookList = (List<MvcApplication1.Models.Book>) ViewData["BookList"];
}
<table class="list_box_table">
@{if(bookList != null)
  {
      for (int i = 0; i < bookList.Count; i++)
      {
          book = bookList[i];
          
   		<tr class="list_box_class" @Html.Raw(String.Format("id=\"list_box_{0}\"", i))>
        <td class="thumbnail" >
      		<img src="~/Images/heroAccent.png">
   		</td>
        <td id="Title" class="title">
            @book.BookName
        </td>
        <td id="Author" class="author">
        	@book.Author
        </td>
        <td id="Course" class="course">
            @book.Course.abbrev()
        </td>
        <td id="Instructor" class="instructor">
        	@book.Course.Instructor
        </td>
        <td id="Semester" class="semester">
        	@book.Course.Semester
        </td>
        </tr>
    <script>
    $(@Html.Raw(String.Format("'#list_box_{0}'", i))).click(function (event) {
        $('#overlay_content').html('<progress max="100"></progress>');
        $('#overlay_parent').css('visibility', 'visible');
        $.post('@Html.Raw(@Url.Action("BookDetails", "Browse", new {BookName=book.BookName, Author=book.Author, Description=book.Description, ISBN=book.ISBN, BookID = book.BookID}))',
                        null, function (result) {
                            $('#overlay_content').html(result);
        });
    });
    </script>
 
        }
    }
}
</table>

 

MvcApplication1/MvcApplication1/Views/Shared/ListingDetails.cshtml
@{
    Layout = null;
    string seller = (string) ViewData["seller"];
    decimal price = (decimal) ViewData["price"];
    int listingID = (int) ViewData["listID"];
    MvcApplication1.Models.Book book = (MvcApplication1.Models.Book) ViewData["book"];
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BookDetails</title>
</head>
<body>
    <div>
        <table>
            <tbody>
                <tr><td>Seller:</td><td>@seller</td></tr>
                <tr><td>Price:</td><td>@String.Format("{0:C}", price)</td></tr>
                <tr /><tr /><tr /><tr /><tr /><tr /><tr />
                <tr><td>Title: </td><td>@book.BookName</td></tr>
                <tr><td>Author: </td><td>@book.Author</td></tr>
                <tr><td>Description: </td><td>desc not impl</td></tr>
                <tr><td>ISBN: </td><td>@book.ISBN</td></tr>
                <tr /><tr /><tr /><tr />
                <tr><td>Course: </td><td>@book.Course.abbrev()</td></tr>
                <tr><td>Instructor: </td><td>Instr not impl</td></tr>
            </tbody>
        </table>

        <button id="close">Close</button>
        @{if(User.Identity.Name.ToLower() != seller){
              <button id="reply">Message Seller</button>
          }
          else
          {    
              <button id="remove">Remove Listing</button>
          }
        }
        

    </div>
</body>
</html>

<script>
    $('#close').click(function () {
        $('#overlay_parent').css('visibility', 'hidden');
    });
    $('#reply').click(function () {
        $.get('@Url.Action("Compose", "Message", new { recipient=@seller })', null, function (result) {
                $('#overlay_content').html(result);

            });
    });
    $('#remove').click(function () {
        $.post('@Url.Action("RemoveListing", "Bookshelf", new { listId=@listingID})', null, function (result) {
            $('#overlay_content').html(result + '<br><button id="CloseDiv">Close</button>');
            $('#CloseDiv').click(function () {
                $('#overlay_parent').css('visibility', 'hidden');
                if (typeof loadBookWishList != 'undefined') {//see if its there
                    loadBookWishList();
                }
                else if (typeof loadBookList != 'undefined') {//see if its there
                    loadBookList();
                }
            });

        });
     });
</script>

MvcApplication1/MvcApplication1/Views/Shared/ListingList.cshtml
@{
    Layout = null;

    MvcApplication1.Models.Listing listing;
    List<MvcApplication1.Models.Listing> list = (List<MvcApplication1.Models.Listing>)ViewData["ListingList"];
    
    
}
<table class="list_box_table">

@{if (list != null)
  {
      for (int i = 0; i < list.Count; i++)
      {
          listing = list[i];
          
   		<tr @Html.Raw(String.Format("id=\"list_box_{0}\"", i)) class="list_box_class">
        <td class="thumbnail">
      		<img  src="~/Images/heroAccent.png">
   		</td>
        <td id="Title" class="title">
            @listing.Book.BookName
        </td>
        <td id="Author" class="author">
        	@listing.Book.Author
        </td> 
        <td id="Seller" class="seller">
            @MvcApplication1.Utils.UserUtils.UserIDtoName(listing.UserID)
        </td>
        <td id="Price" class="price">
            @String.Format("{0:C}", listing.Price)
        </td>
        </tr>
<script>
    $(@Html.Raw(String.Format("'#list_box_{0}'", i))).click(function (event) {
        $('#overlay_content').html('<progress max="100"></progress>');
        $('#overlay_parent').css('visibility', 'visible');
        $.post('@Html.Raw(@Url.Action("ListingDetails", "Bookshelf", new { bookID = listing.BookID, seller = listing.UserID, price = listing.Price, BookName = listing.Book.BookName, Author = listing.Book.Author, Description = listing.Book.Description, ISBN = listing.Book.ISBN, CourseID = listing.Book.CourseID, ListID = listing.ListID }))',
                        null, function (result) {
                            $('#overlay_content').html(result);
        });


    });
</script>
      }
  }
}
</table>