MvcApplication1/MvcApplication1/Controllers/BookshelfController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;
using MvcApplication1.Utils;

namespace MvcApplication1.Controllers
{
    public class BookshelfController : Controller
    {
        const String Ipsum = "Lorem ipsum dolor sit amet, quaeque nominati in ius, eum ut fastidii vivendum tincidunt. Ea eos discere corpora senserit.";
        //
        // GET: /Bookshelf/

        public ActionResult Bookshelf()
        {
            return View();
        }
        public ActionResult Wishlist()
        {
            return View("~/Views/Bookshelf/Wishlist.cshtml");
        }
        public ActionResult GetBookshelf()
        {
            /*
            //TODO get user's listings instead of hardcoded listing IDs
            int[] IDs = { 1, 2, 3, 4, 5 };

            List<Listing> list = new List<Listing>();
            for (int i = 0; i < IDs.Length; i++)
            {
                list.Add(ListingUtils.getListing(IDs[i]));
            }
            */
            List<Listing> listingList;

            using (TestDbContext db = new TestDbContext())
            {
                //scrub db of all expired listings before fetching
                removeExpiredListings(db);

                int accountid = UserUtils.UserNametoID(User.Identity.Name);

                IQueryable<Listing> listings = from l in db.Listings
                                               orderby l.ListDate descending
                                               where l.UserID == accountid
                                               where l.ListType == 0 //0 is books to sell
                                               select l;

                listingList = listings.ToList<Listing>();
                foreach (var l in listingList)
                {
                    if (l != null)
                    {
                        //due to lazy loading, resolve all foreign key references
                        //listing.UserProfile = listing.UserProfile;
                        l.Book = l.Book;
                        l.Book.Course = l.Book.Course;
                    }
                    else
                    {
                        //no listing with the given ID, report error?
                    }
                }
            }


            ViewData["ListingList"] = listingList;

            return View("~/Views/Shared/ListingList.cshtml");
        }

        public ActionResult GetWishlist()
        {
            List<Listing> listingList;
            using (TestDbContext db = new TestDbContext())
            {

                int accountid = UserUtils.UserNametoID(User.Identity.Name);

                IQueryable<Listing> listings = from l in db.Listings
                                               orderby l.ListDate descending
                                               where l.UserID == accountid
                                               where l.ListType == 1 //1 is books to buy
                                               select l;

                listingList = listings.ToList<Listing>();
                foreach (var l in listingList)
                {
                    if (l != null)
                    {
                        //due to lazy loading, resolve all foreign key references
                        //listing.UserProfile = listing.UserProfile;
                        l.Book = l.Book;
                        l.Book.Course = l.Book.Course;
                    }
                    else
                    {
                        //no listing with the given ID, report error?
                    }
                }
            }
            ViewData["ListingList"] = listingList;
            return View("~/Views/Shared/ListingList.cshtml");
        }

        public ActionResult PopupTest(int id)
        {
            ViewData["id"] = id;
            return View("~/Views/Bookshelf/PopupTest.cshtml");
        }

        public ActionResult AddListing(String bookName = "none", String author = "none", String description = "none", String course = "none", String iSBN = "none", Decimal price = 0.00m, int listingType = -1)
        {
            if (listingType == -1) return Content("Book Add Failed");
            String user = User.Identity.Name;
            if (user != null)
            {
                //getUserID from logans utility
                using (TestDbContext db = new TestDbContext())
                {
                    Book bookToCheck = new Book();
                    bookToCheck.BookName = bookName;
                    bookToCheck.Author = author;
                    bookToCheck.Description = Ipsum;
                    bookToCheck.ISBN = iSBN;

                    //TODO set the fields of book accoring to the data in the dialog
                    Listing listToAdd = new Listing();

                    listToAdd.UserID = UserUtils.UserNametoID(user);
                    //adduser to listing
                    //see if book exists in database
                    //Book bookChecked = db.Books.Where(b => b.BookName.Equals(bookToCheck.BookName) && b.Author.Equals(bookToCheck.Author)).First();
                    var myBook = (from b in db.Books
                                  where b.BookName == bookName
                                  where b.Author == author
                                  select b).ToList();
                    if (myBook.Count > 0)
                    {
                        if (myBook[0] != null && myBook[0].BookID != null)
                        {
                            listToAdd.BookID = myBook[0].BookID;
                        }
                    }
                    else
                    {
                        Course tempCourse = new Course();
                        bookToCheck.Course = tempCourse;
                        tempCourse.CourseName = "not implimented";
                        tempCourse.CourseNumber = 123;
                        var courseFromDB = (from c in db.Courses
                                           where c.CourseName == tempCourse.CourseName
                                           where c.CourseNumber == tempCourse.CourseNumber
                                           select c).ToList();
                        if (courseFromDB.Count > 0)
                        {
                            bookToCheck.Course = courseFromDB[0];
                            bookToCheck.CourseID = courseFromDB[0].CourseID;
                        }
                        else
                        {
                            bookToCheck.Course = tempCourse;
                        }

                        db.Books.Add(bookToCheck);
                        db.SaveChanges();
                        myBook = (from b in db.Books
                                  where b.BookName == bookName
                                  where b.Author == author
                                  select b).ToList();
                        listToAdd.BookID = myBook[0].BookID;
                    }
                    //ifnot add the book to the database
                    //add the bookID to the Listing
                    //add the Listing date to the Listing object
                    listToAdd.ListDate = DateTime.Now;
                    listToAdd.Price = Convert.ToDecimal(price);
                    //set list type to what ever it needs to be
                    listToAdd.ListType = listingType;
                    //add the liting to the database
                    db.Listings.Add(listToAdd);
                    db.SaveChanges();
                }
            }
            return Content("Book Added");
        }

        [HttpPost]
        public ActionResult RemoveListing(int listId)
        {
            using (TestDbContext db = new TestDbContext())
            {
                var listToRemove = db.Listings.Find(listId);
                if (listToRemove != null)
                {
                    db.Listings.Remove(listToRemove);
                    db.SaveChanges();
                    return Content("Listing Removed");
                }
                else
                {
                    return Content("Remove Failed");
                }
            }
        }

        [HttpPost]
        public ActionResult AddBook(String bookName = "none", String author = "none", String description = "none", String course = "none", String iSBN = "none", decimal price = 0.00m)
        {
            return AddListing(bookName, author, description, course, iSBN, price, 0);
        }

        [HttpPost]
        public ActionResult AddBookToWishlist(String bookName = "none", String author = "none", String description = "none", String course = "none", String iSBN = "none", decimal price = 0.00m)
        {
            return AddListing(bookName, author, description, course, iSBN, price, 1);
        }

        [HttpGet]
        public ActionResult AddBookDialog()
        {
            return View("~/Views/Bookshelf/AddBook.cshtml");
        }

        [HttpGet]
        public ActionResult AddBookToWishlistDialog()
        {
            return View("~/Views/Bookshelf/AddBookToWishlist.cshtml");
        }

        //listing details popup getter
        public ActionResult ListingDetails(string seller, decimal? price, MvcApplication1.Models.Book clickedBook, int listID)
        {
            //if (clickedBook.CourseID > 0)
            //{
            //    using (TestDbContext db = new TestDbContext())
            //    {
            //        clickedBook.Course = db.Courses.Find(clickedBook.CourseID);
            //    }
            //}

            //currently seller is being passed as an ID, this will probably change


            //ViewData["seller"] = (seller == null) ? "" : seller;
            ViewData["seller"] = UserUtils.UserIDtoName(Convert.ToInt32(seller));
            ViewData["price"] = (price == null) ? 0m : price;

MvcApplication1/MvcApplication1/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;
using MvcApplication1.Utils;
using System.Net.Http;
using System.Net;
using System.Net.Http.Formatting;

namespace MvcApplication1.Controllers
{
    public class BrowseController : Controller
    {
        //
        // GET: /Browse/

        public ActionResult Browse()
        {
            return View();
        }

        public ActionResult GetBookList()
        {
            //test list of IDs to populate the list based on test book table
            //int[] IDs = { 1, 2, 3, 4, 5, 6 };

            //List<Book> bookList = new List<Book>();
            //for(int i = 0; i < IDs.Length; i++)
            //{
            //    bookList.Add(BookUtils.getBook(IDs[i]));
            //}

            //ViewData["BookList"] = bookList;
            //ViewData["isListing"] = true;
            //return View("~/Views/Shared/BookList.cshtml");



            List<Book> bookList;
            using (TestDbContext db = new TestDbContext())
            {

                IQueryable<Book> books = from b in db.Books
         //                                      orderby b.BookName
                                               select b;

                bookList = books.ToList<Book>();
                foreach (var b in bookList)
                {
                    if (b != null)
                    {
                        //due to lazy loading, resolve all foreign key references
                        //listing.UserProfile = listing.UserProfile;
                        b.Course = b.Course;
                        b.Course.Books = b.Course.Books;
                    }
                    else
                    {
                        //no listing with the given ID, report error?
                    }
                }
            }


            ViewData["BookList"] = bookList;
            ViewData["isListing"] = true;

            return View("~/Views/Shared/BookList.cshtml");
        }

        public object AutoComplete(string term)
        {
            using(TestDbContext db = new TestDbContext())
            {
                int courseNum;
                bool success;
                success = Int32.TryParse(term, out courseNum);
                var returnArr = db.Books.Where(b => b.BookName.StartsWith(term) ||
                    b.Course.CourseName.StartsWith(term) ||
                    (success && courseNum == b.Course.CourseNumber) ||
                    b.Author.StartsWith(term)).Select(b => new
                    {
                        value = b.BookName.Trim()
                    }).Take(5).ToArray();
               return this.Json(returnArr, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Search(int courseNum = 0, string bookName = "",
                                    string courseName = "", string author = "")
        {
        if (courseNum != 0)
            {
                ViewData["courseNum"] = courseNum;
            }
            if (!bookName.Equals(""))
            {
                ViewData["bookName"] = bookName;
            }
            if (!courseName.Equals(""))
            {
                ViewData["courseName"] = courseName;
            }
            if (!author.Equals(""))
            {
                ViewData["author"] = courseName;
            }
            return View("~/Views/Search/Search.cshtml");
        }

public ActionResult GetListingList(int courseNum = 0, string bookName = "",
                                    string courseName = "", string author = "")
        {
            using(TestDbContext db = new TestDbContext())
            {
                List<Listing> ListingList = db.Listings.Where(b => !bookName.Equals("") && b.Book.BookName.StartsWith(bookName) ||
                       !courseName.Equals("") && b.Book.Course.CourseName.StartsWith(courseName) ||
                       (courseNum == b.Book.Course.CourseNumber) ||
                      !author.Equals("")&& b.Book.Author.StartsWith(author)).ToList();
                for (int i = 0; i < ListingList.Count(); i++)
                {
                    ListingList.ElementAt(i).Book = ListingList.ElementAt(i).Book;
                }
                       ViewData["ListingList"] = ListingList;
                       ViewResult view = View("~/Views/Shared/ListingList.cshtml");
                       return view;
            }
        }

        //book details popup getter
        public ActionResult BookDetails(MvcApplication1.Models.Book clickedBook = null)//)
        {
            if (clickedBook == null)
            {
                return Content("error");
            }
            if (clickedBook.CourseID > 0)
            {
                using (TestDbContext db = new TestDbContext())
                {
                    clickedBook.Course = db.Courses.Find(clickedBook.CourseID);
                }
            }

            
            //get available listings for book

            Book resolvedBook = null;

            using (TestDbContext db = new TestDbContext())
            {

                int accountid = UserUtils.UserNametoID(User.Identity.Name);

                IQueryable<Book> books = from b in db.Books 
                                               where b.BookID == clickedBook.BookID
                                               select b;
                if (books.Count() > 0)
                {
                    resolvedBook = books.First();
                    //probably more loading here than needed
                    resolvedBook.Course = resolvedBook.Course;
                    resolvedBook.Course.Books = resolvedBook.Course.Books;
                    resolvedBook.Listings = resolvedBook.Listings;
                }
                
            }
            
            
            //pass back available listings
            ViewData["book"] = resolvedBook;
            return View("~/Views/Shared/BookDetails.cshtml");
        }

        [HttpGet]
        public ActionResult getBook(string bookName)
        {
            using (TestDbContext db = new TestDbContext())
            {
                Book book;
                var books = (from b in db.Books
                             where b.BookName == bookName
                             select b).ToList();
                if (books.Count > 0 && books[0] != null)
                {
                    book = books[0];

                    book.ISBN = book.ISBN == null ? "" : book.ISBN.Trim();
                    book.Author = book.Author == null ? "" : book.Author.Trim();
                    book.Description = book.Description == null ? "" : book.Description.Trim();

                    if (book.Course == null)
                    {
                        book.Course = new Course();
                        book.Course.CourseName = "";
                    }
                    else if (book.Course.CourseName == null)
                    {
                        book.Course.CourseName = "";
                    }
                }
                else
                {
                    book = new Book();
                    book.BookName = "";
                    book.Course = new Course();
                    book.Course.CourseName = "";
                    book.Author = "";
                    book.ISBN = "";
                    book.Description = "";
                }

                var retBook = new
                {
                    Author = book.Author,
                    ISBN = book.ISBN,
                    CourseName = book.Course.CourseName,
                    Description = book.Description,
                };

                return Json(retBook, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MvcApplication1/MvcApplication1/Views/Bookshelf/AddBook.cshtml
@{
    Layout = null;
    ViewBag.Title = "List a Book";
}

<script>

    /* unhide popup and populate it with compose form */
    var cancel = function () {
        //unhide popup div
        $('#overlay_parent').css('visibility', 'hidden');
    };

    var addListing = function () {
        //send linsting data to bookshelf controler
        //reload book shelf list after listing is added
        $.post('Bookshelf/AddBook', $('#addBookForm').serialize(), function (result) {
            $('#overlay_content').html(result + '<br><button id="CloseDiv">Close</button>');
            $('#CloseDiv').click(function () {
                $('#overlay_parent').css('visibility', 'hidden');
                if (loadBookList) {//see if its there
                    loadBookList();
                }
            });
        });
    }

    $('#BookName').autocomplete({
        source: '@Url.Action("AutoComplete", "Browse")',
        minLength: 2,
        select: function (event, ui) {
            $.ajax({
                url: '@Url.Action("getBook", "Browse")',
                type: 'GET',
                dataType: 'json',
                cache: false,
                data: { bookName: ui.item.value },
                success: function (book) {
                    $('#iSBN').val(book.ISBN);
                    $('#author').val(book.Author);
                    $('#course').val(book.CourseName);
                    //$('#description').val(book.Description);
                }
            });
        }
    });

</script>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <table>
        <tbody>

        <tr>
        <td>

        <form method="post" id="addBookForm" action='@Url.Action("AddBook", "Bookshelf")'>
        <table>
        <tbody>
        <tr><td>Book Name:</td><td><textarea id="BookName" name="bookName" rows="1" cols="65"></textarea></td></tr>
        <tr><td>ISBN:</td><td><textarea id="iSBN" name="iSBN" rows="1" cols="65" ></textarea></td></tr>
        <tr><td>Author:</td><td><textarea id="author" name="author" rows="1" cols="65"></textarea></td></tr>
        <tr><td>Course:</td><td><textarea id="course" name="course" rows="1" cols="65"></textarea></td></tr>
        <tr><td>Price:</td><td><textarea id="price" name="price" rows="1" cols="65"></textarea></td></tr>
        </tbody>
        </table>

        <input type="button" value="Add Listing" id="addListingButton" onclick="addListing()" />
        <input type="button" value="Cancel" id="cancelButton" onclick="cancel()"/>
        </form>
        </tbody>
        </table>
    </div>
</body>
</html>

MvcApplication1/MvcApplication1/Views/Bookshelf/AddBookToWishlist.cshtml
@{
    Layout = null;
    ViewBag.Title = "List a Book";
}

<script>

    /* unhide popup and populate it with compose form */
    var cancel = function () {
        //unhide popup div
        $('#overlay_parent').css('visibility', 'hidden');
    };

    var addListing = function () {
        //send linsting data to bookshelf controler
        //reload book shelf list after listing is added
        $.post('@Url.Action("AddBookToWIshlist", "Bookshelf")', $('#addBookForm').serialize(), function (result) {
            $('#overlay_content').html(result + '<br><button id="CloseDiv">Close</button>');
            $('#CloseDiv').click(function () {
                $('#overlay_parent').css('visibility', 'hidden');
                if (typeof loadBookWishList != 'undefined') {//see if its there
                    loadBookWishList();
                }
            });
        });
    }

    $('#BookName').autocomplete({
        source: '@Url.Action("AutoComplete", "Browse")',
        minLength: 2,
        select: function (event, ui) {
            $.ajax({
                url: '@Url.Action("getBook", "Browse")',
                type: 'GET',
                dataType: 'json',
                cache: false,
                data: { bookName: ui.item.value },
                success: function (book) {
                    $('#iSBN').val(book.ISBN);
                    $('#author').val(book.Author);
                    $('#course').val(book.CourseName);
                    //$('#description').val(book.Description);
                }
            });
        }
    });

</script>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <table>
        <tbody>

        <tr>
        <td>

        <form method="post" id="addBookForm" action='@Url.Action("AddBookToWishlist", "Bookshelf")'>
        <table>
        <tbody>
        <tr><td>Book Name:</td><td><textarea id="BookName" name="bookName" rows="1" cols="65"></textarea></td></tr>
        <tr><td>ISBN:</td><td><textarea id="iSBN" name="iSBN" rows="1" cols="65" ></textarea></td></tr>
        <tr><td>Author:</td><td><textarea id="author" name="author" rows="1" cols="65"></textarea></td></tr>
        <tr><td>Course:</td><td><textarea id="course" name="course" rows="1" cols="65"></textarea></td></tr>
        <tr><td>Price:</td><td><textarea id="price" name="price" rows="1" cols="65"></textarea></td></tr>
        </tbody>
        </table>

        <input type="button" value="Add Listing" id="addListingButton" onclick="addListing()" />
        <input type="button" value="Cancel" id="cancelButton" onclick="cancel()"/>
        </form>
        </tbody>
        </table>
    </div>
</body>
</html>

MvcApplication1/MvcApplication1/Views/Bookshelf/Bookshelf.cshtml
@{
    ViewBag.Title = "Bookshelf";
}



<script>
    var addBook = function () {
        $('#overlay_parent').css('visibility', 'visible');
        $('#overlay_content').html('<progress max="100"></progress>');
        //call funciton to grab html
        $.get('@Url.Action("AddBookDialog", "Bookshelf")', null, function (result) {
            $('#overlay_content').html(result);
        });
    };
    var loadBookList = function () {
        $("#bookList").html('<progress max="100"></progress>');
        $.get('@Url.Action("GetBookshelf","Bookshelf")', null, function (result) {
            $("#bookList").html(result);

        });
    };
    loadBookList();
</script>

<input type="button" value="Add a book" onclick="addBook()" />
<div style ="width:100%" id="bookList"></div>

MvcApplication1/MvcApplication1/Views/Bookshelf/PopupTest.cshtml
@{
    Layout = null;
}

<div>
    This was opened by @Html.Encode(ViewData["id"])
    <button id="close">Close</button>
</div>
<script>
    $('#close').click(function () {
        $('#overlay_parent').css('visibility', 'hidden');
    });
</script>

MvcApplication1/MvcApplication1/Views/Bookshelf/Wishlist.cshtml
@{
    ViewBag.Title = "Wishlist";
}



<script>
    var addBook = function () {
        $('#overlay_parent').css('visibility', 'visible');
        $('#overlay_content').html('<progress max="100"></progress>');
        //call funciton to grab html
        $.get('@Url.Action("AddBooktoWishlistDialog", "Bookshelf")', null, function (result) {
            $('#overlay_content').html(result);
        });
    };
    var loadBookWishList = function () {
        $("#bookList").html('<progress max="100"></progress>');
        $.get('@Url.Action("GetWishlist","Bookshelf")', null, function (result) {
            $("#bookList").html(result);

        });
    };
    loadBookWishList();
</script>

<input type="button" value="Add a book" onclick="addBook()" />
<div style ="width:100%" id="bookList"></div>